# Generated by Django 3.2.6 on 2023-04-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_attendance_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='time',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='date',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='time',
        ),
        migrations.AddField(
            model_name='attendance',
            name='date_time',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='date_time',
            field=models.TextField(null=True),
        ),
    ]
