# Generated by Django 3.2.6 on 2023-04-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230410_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='image',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='image',
            field=models.BinaryField(null=True),
        ),
    ]
