# Generated by Django 4.2.2 on 2023-06-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_attendance_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
