# Generated by Django 4.2.2 on 2023-06-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_attendance_date_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='unknown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=191)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('image', models.BinaryField(null=True)),
            ],
            options={
                'db_table': 'unknown',
            },
        ),
    ]
