# Generated by Django 4.2.6 on 2024-02-13 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_unknown_date_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rejected_unknown',
        ),
    ]
