# Generated by Django 4.2.6 on 2024-02-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_delete_rejected_unknown'),
    ]

    operations = [
        migrations.CreateModel(
            name='rejected_unknown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=191)),
                ('date_time', models.DateTimeField()),
                ('image', models.BinaryField(null=True)),
            ],
            options={
                'db_table': 'rejected_unknown',
            },
        ),
    ]
